// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqA8wsWk9k_v_BPHpM7DfOYzMzCYdm0Bw',
    appId: '1:220038025968:android:37dce3c6901b2d3c472835',
    messagingSenderId: '220038025968',
    projectId: 'fwitter-62ccc',
    storageBucket: 'fwitter-62ccc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCQLzRYB7x5MoH5wtIEumvkgFoPe-K9YE',
    appId: '1:220038025968:ios:b819aebc7e373040472835',
    messagingSenderId: '220038025968',
    projectId: 'fwitter-62ccc',
    storageBucket: 'fwitter-62ccc.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUE-QH3oFvtBUW8791LTZvUlzVAl2FQNs',
    appId: '1:220038025968:web:3d7c90f17ed6e188472835',
    messagingSenderId: '220038025968',
    projectId: 'fwitter-62ccc',
    authDomain: 'fwitter-62ccc.firebaseapp.com',
    storageBucket: 'fwitter-62ccc.appspot.com',
  );

}